version: 0.0.{build}

assembly_info:
    patch: true
    file: DigitimateSharp\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-alpha'

cache:
    - packages -> **\packages.config

before_build:
    - nuget restore

build:
    project: DigitimateSharp\DigitimateSharp.csproj

deploy:
    provider: GitHub
    artifact: /.*\.nupkg/
    draft: true
    prerelease: true
    on:
        branch: master
        appveyor_repo_tag: false
    auth_token:
        secure: SaAWccjRLZHFX/3wGSX8sDSQbav0bsNPl4+4cAWUEiJe4qmKc9Nj/PCTQlHSnUz5