version: 0.0.{build}

assembly_info:
    patch: true
    file: DigitimateSharp\Properties\AssemblyInfo.cs
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}-alpha'

cache:
    - packages -> **\packages.config

before_build:
    - nuget restore

build:
    project: DigitimateSharp\DigitimateSharp.csproj

after_build:
    - cd DigitimateSharp
    - nuget pack DigitimateSharp.csproj -Build -Symbols -Properties Configuration=Release
    - nuget 'push DigitimateSharp\DigitimateSharp.{version}.0.nupkg' -ApiKey  becc3a66-c382-496b-9f43-bedad95d9206

artifacts:
    - path: DigitimateSharp\*.nupkg