version: 1.0.{build}

branches:
    only:
        - master

assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

cache: packages -> **\packages.config

before_build:
    nuget restore

build:
    publish_nuget: true
    verbosity: normal

artifacts:
    path: DigitimateSharp\*.nupkg

deploy:
    provider: NuGet
    api_key:
        secure: L9eqPVm+ci7BmCdJraRqcuelxbdr8rMh2fnc1Qsd66Qg9U+7dm5NGY4XKv0+WAff