version: 0.1.{build}

branches:
    only:
        - master

assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

cache: packages -> **\packages.config

before_build:
    - nuget restore

build:
    verbosity: normal

artifacts:
    path: DigitimateSharp\*.nupkg